{{- if .Values.publicIngress.enabled -}}
{{- $fullName := include "app.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-public
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.publicIngress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  ingressClassName: {{ .Values.publicIngress.className }}
  tls:
{{- range .Values.publicIngress.hosts }}
    - hosts:
        - {{ . }}
{{- end }}
  rules:
{{- range .Values.publicIngress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: /ping
            pathType: Exact
            backend:
              service:
                name: {{ $fullName }}
                port:
                  name: http
{{- end }}
{{- end }}
