apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.fullname" . }}
type: Opaque
data:
  deployHost: {{ .Values.deploy.host | b64enc | quote }}
  secretKeyBase: {{ .Values.deploy.secretKeyBase | b64enc | quote }}
  database_name: {{ .Values.branch.name | b64enc | quote }}
  settings__environment: {{ .Values.deploy.settings__environment | b64enc | quote }}
  settings__credentials__use_case_1__description: {{ .Values.deploy.settings__credentials__description | b64enc | quote }}
  settings__credentials__use_case_1__host: {{ .Values.deploy.settings__credentials__host | b64enc | quote }}
  settings__credentials__use_case_1__hmrc_client_secret: {{ .Values.deploy.settings__credentials__hmrc_client_secret | b64enc | quote }}
  settings__credentials__use_case_1__hmrc_client_id: {{ .Values.deploy.settings__credentials__hmrc_client_id | b64enc | quote }}
  settings__credentials__use_case_1__hmrc_totp_secret: {{ .Values.deploy.settings__credentials__hmrc_totp_secret | b64enc | quote }}
