apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.fullname" . }}
type: Opaque
data:
  deployHost: {{ .Values.deploy.host | b64enc | quote }}
  {{- if eq .Values.deploy.settings__sentry__environment "uat" }}
  database_name: {{ .Values.database.name | b64enc | quote }}
  {{ end }}
  settings__credentials__use_case_one__host: {{ .Values.deploy.settings__credentials__use_case_one__host | b64enc | quote }}
  settings__credentials__use_case_one__hmrc_client_secret: {{ .Values.deploy.settings__credentials__use_case_one__hmrc_client_secret | b64enc | quote }}
  settings__credentials__use_case_one__hmrc_client_id: {{ .Values.deploy.settings__credentials__use_case_one__hmrc_client_id | b64enc | quote }}
  settings__credentials__use_case_one__hmrc_totp_secret: {{ .Values.deploy.settings__credentials__use_case_one__hmrc_totp_secret | b64enc | quote }}
  settings__credentials__use_case_two__host: {{ .Values.deploy.settings__credentials__use_case_two__host | b64enc | quote }}
  settings__credentials__use_case_two__hmrc_client_secret: {{ .Values.deploy.settings__credentials__use_case_two__hmrc_client_secret | b64enc | quote }}
  settings__credentials__use_case_two__hmrc_client_id: {{ .Values.deploy.settings__credentials__use_case_two__hmrc_client_id | b64enc | quote }}
  settings__credentials__use_case_two__hmrc_totp_secret: {{ .Values.deploy.settings__credentials__use_case_two__hmrc_totp_secret | b64enc | quote }}
  settings__credentials__use_case_three__host: {{ .Values.deploy.settings__credentials__use_case_three__host | b64enc | quote }}
  settings__credentials__use_case_three__hmrc_client_secret: {{ .Values.deploy.settings__credentials__use_case_three__hmrc_client_secret | b64enc | quote }}
  settings__credentials__use_case_three__hmrc_client_id: {{ .Values.deploy.settings__credentials__use_case_three__hmrc_client_id | b64enc | quote }}
  settings__credentials__use_case_three__hmrc_totp_secret: {{ .Values.deploy.settings__credentials__use_case_three__hmrc_totp_secret | b64enc | quote }}
  settings__credentials__use_case_four__host: {{ .Values.deploy.settings__credentials__use_case_four__host | b64enc | quote }}
  settings__credentials__use_case_four__hmrc_client_secret: {{ .Values.deploy.settings__credentials__use_case_four__hmrc_client_secret | b64enc | quote }}
  settings__credentials__use_case_four__hmrc_client_id: {{ .Values.deploy.settings__credentials__use_case_four__hmrc_client_id | b64enc | quote }}
  settings__credentials__use_case_four__hmrc_totp_secret: {{ .Values.deploy.settings__credentials__use_case_four__hmrc_totp_secret | b64enc | quote }}
  {{- if eq .Values.deploy.settings__environment "non-live" }}
  settings__smoke_test__use_case_one__first_name: {{ .Values.smoke_test.use_case_one.first_name | b64enc | quote }}
  settings__smoke_test__use_case_one__last_name: {{ .Values.smoke_test.use_case_one.last_name | b64enc | quote }}
  settings__smoke_test__use_case_one__nino: {{ .Values.smoke_test.use_case_one.nino | b64enc | quote }}
  settings__smoke_test__use_case_one__dob: {{ .Values.smoke_test.use_case_one.dob | b64enc | quote }}
  settings__smoke_test__use_case_one__start_date: {{ .Values.smoke_test.use_case_one.start_date | b64enc | quote }}
  settings__smoke_test__use_case_one__end_date: {{ .Values.smoke_test.use_case_one.end_date | b64enc | quote }}
  settings__smoke_test__use_case_one__correlation_id: {{ .Values.smoke_test.use_case_one.correlation_id | b64enc | quote }}
  settings__smoke_test__use_case_two__first_name: {{ .Values.smoke_test.use_case_two.first_name | b64enc | quote }}
  settings__smoke_test__use_case_two__last_name: {{ .Values.smoke_test.use_case_two.last_name | b64enc | quote }}
  settings__smoke_test__use_case_two__nino: {{ .Values.smoke_test.use_case_two.nino | b64enc | quote }}
  settings__smoke_test__use_case_two__dob: {{ .Values.smoke_test.use_case_two.dob | b64enc | quote }}
  settings__smoke_test__use_case_two__start_date: {{ .Values.smoke_test.use_case_two.start_date | b64enc | quote }}
  settings__smoke_test__use_case_two__end_date: {{ .Values.smoke_test.use_case_two.end_date | b64enc | quote }}
  settings__smoke_test__use_case_two__correlation_id: {{ .Values.smoke_test.use_case_two.correlation_id | b64enc | quote }}
  settings__smoke_test__use_case_three__first_name: {{ .Values.smoke_test.use_case_three.first_name | b64enc | quote }}
  settings__smoke_test__use_case_three__last_name: {{ .Values.smoke_test.use_case_three.last_name | b64enc | quote }}
  settings__smoke_test__use_case_three__nino: {{ .Values.smoke_test.use_case_three.nino | b64enc | quote }}
  settings__smoke_test__use_case_three__dob: {{ .Values.smoke_test.use_case_three.dob | b64enc | quote }}
  settings__smoke_test__use_case_three__start_date: {{ .Values.smoke_test.use_case_three.start_date | b64enc | quote }}
  settings__smoke_test__use_case_three__end_date: {{ .Values.smoke_test.use_case_three.end_date | b64enc | quote }}
  settings__smoke_test__use_case_three__correlation_id: {{ .Values.smoke_test.use_case_three.correlation_id | b64enc | quote }}
  settings__smoke_test__use_case_four__first_name: {{ .Values.smoke_test.use_case_four.first_name | b64enc | quote }}
  settings__smoke_test__use_case_four__last_name: {{ .Values.smoke_test.use_case_four.last_name | b64enc | quote }}
  settings__smoke_test__use_case_four__nino: {{ .Values.smoke_test.use_case_four.nino | b64enc | quote }}
  settings__smoke_test__use_case_four__dob: {{ .Values.smoke_test.use_case_four.dob | b64enc | quote }}
  settings__smoke_test__use_case_four__start_date: {{ .Values.smoke_test.use_case_four.start_date | b64enc | quote }}
  settings__smoke_test__use_case_four__end_date: {{ .Values.smoke_test.use_case_four.end_date | b64enc | quote }}
  settings__smoke_test__use_case_four__correlation_id: {{ .Values.smoke_test.use_case_four.correlation_id | b64enc | quote }}
  {{ end }}

