apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.fullname" . }}
type: Opaque
data:
  deployHost: {{ .Values.deploy.host | b64enc | quote }}
  secretKeyBase: {{ .Values.deploy.secretKeyBase | b64enc | quote }}
  database_name: {{ .Values.branch.name | b64enc | quote }}
  settings__environment: {{ .Values.deploy.settings__environment | b64enc | quote }}
  settings__credentials__use_case_one__description: {{ .Values.deploy.settings__credentials__use_case_one__description | b64enc | quote }}
  settings__credentials__use_case_one__host: {{ .Values.deploy.settings__credentials__use_case_one__host | b64enc | quote }}
  settings__credentials__use_case_one__hmrc_client_secret: {{ .Values.deploy.settings__credentials__use_case_one__hmrc_client_secret | b64enc | quote }}
  settings__credentials__use_case_one__hmrc_client_id: {{ .Values.deploy.settings__credentials__use_case_one__hmrc_client_id | b64enc | quote }}
  settings__credentials__use_case_one__hmrc_totp_secret: {{ .Values.deploy.settings__credentials__use_case_one__hmrc_totp_secret | b64enc | quote }}
  settings__sidekiq__username: {{ .Values.deploy.settings__sidekiq__username | b64enc | quote }}
  settings__sidekiq__web_ui_password: {{ .Values.deploy.settings__sidekiq__web_ui_password | b64enc | quote }}
  settings__sentry__dsn: {{ .Values.deploy.settings__sentry__dsn | b64enc | quote }}
  settings__sentry__environment: {{ .Values.deploy.settings__sentry__environment | b64enc | quote }}
  settings__smoke_test__use_case_one__first_name: {{ .Values.deploy.settings__smoke_test__use_case_one__first_name | b64enc | quote }}
  settings__smoke_test__use_case_one__last_name: {{ .Values.deploy.settings__smoke_test__use_case_one__last_name | b64enc | quote }}
  settings__smoke_test__use_case_one__nino: {{ .Values.deploy.settings__smoke_test__use_case_one__nino | b64enc | quote }}
  settings__smoke_test__use_case_one__dob: {{ .Values.deploy.settings__smoke_test__use_case_one__dob | b64enc | quote }}
  settings__smoke_test__use_case_one__start_date: {{ .Values.deploy.settings__smoke_test__use_case_one__start_date | b64enc | quote }}
  settings__smoke_test__use_case_one__end_date: {{ .Values.deploy.settings__smoke_test__use_case_one__end_date | b64enc | quote }}
  settings__smoke_test__use_case_one__correlation_id: {{ .Values.deploy.settings__smoke_test__use_case_one__correlation_id | b64enc | quote }}
