version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  allow:
    - dependency-type: "all"
  schedule:
    interval: daily
    time: "21:00"
    timezone: Europe/London
  open-pull-requests-limit: 5
  target-branch: main
  groups:
    rswag-gems:
      patterns:
        - "rswag-*"
    aws-gems:
      patterns:
        - "aws-*"
    rubocop-gems:
      patterns:
        - "rubocop-*"
