version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    allow:
      - dependency-type: "all"
    schedule:
      interval: weekly
      day: sunday
      time: "21:00"
      timezone: Europe/London
    ignore:
      - dependency-name: rails
        versions:
          - ">= 8.0.0"
      - dependency-name: action*
        versions:
          - ">= 8.0.0"
      - dependency-name: active*
        versions:
          - ">= 8.0.0"
    groups:
      bundler:
        patterns:
          - "*"
    open-pull-requests-limit: 5
    reviewers:
      - "ministryofjustice/laa-apply-for-legal-aid"
