version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  allow:
    - dependency-type: "all"
  schedule:
    interval: daily
    time: "21:00"
    timezone: Europe/London
  open-pull-requests-limit: 5
  target-branch: main
  ignore:
    - dependency-name: "doorkeeper"
      versions: ["~> 5.5.4"]
