---
openapi: 3.0.1
info:
  title: LAA HMRC Interface Service
  description: This Service facilitates the HMRC API access for the LAA Use Cases
  version: v1
paths:
  "/api/v1/submission/create/{use_case}":
    post:
      summary: Create new submission
      tags:
      - Submissions
      security:
      - oAuth: []
      parameters:
      - name: use_case
        in: path
        required: true
        type: string
        description: The use case you wish to request
        schema:
          enum:
          - one
          - two
          - three
          - four
      description: Create a submission record and start the HMRC process asynchronously
      responses:
        '202':
          description: Accepted
        '401':
          description: 'Error: Unauthorized'
        '400':
          description: Bad request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                filter:
                  type: object
                  properties:
                    first_name:
                      type: String
                      example: Langley
                    last_name:
                      type: String
                      example: Yorke
                    nino:
                      type: String
                      example: MN212451D
                    dob:
                      type: Date
                      example: '1992-07-22'
                    start_date:
                      type: Date
                      example: '2020-08-01'
                    end_date:
                      type: Date
                      example: '2020-10-01'
        required: true
  "/api/v1/submission/result/{id}":
    get:
      summary: Retrieves a submission
      tags:
      - Submissions
      security:
      - oAuth: []
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Submission failed
        '202':
          description: Submission still processing
        '500':
          description: Submission complete but no result object is present
        '404':
          description: Submission not found
        '401':
          description: 'Error: Unauthorized'
        '400':
          description: Bad request
  "/smoke-test/{use_case}":
    get:
      summary: individual use_case smoke-test
      description: Run a smoke test for chosen use_case
      tags:
      - Smoke tests
      parameters:
      - name: use_case
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: success
          content:
            application/json:
              example:
                smoke_test_one_result: true
        '500':
          description: internal server error
          content:
            application/json:
              example:
                smoke_test_one_result: false
  "/smoke-test":
    get:
      summary: call smoke_test
      description: Fetch smoke_test results that have been generated within the last
        hour
      tags:
      - Smoke tests
      responses:
        '200':
          description: success
          content:
            application/json:
              example:
                smoke_test_result:
                  use_case_one: true
                  use_case_two: true
                  use_case_three: true
                  use_case_four: true
        '500':
          description: internal server error
          content:
            application/json:
              example:
                smoke_test_result:
                  use_case_one: false
                  use_case_two: true
                  use_case_three: true
                  use_case_four: true
components:
  securitySchemes:
    oAuth:
      in: header
      type: oauth2
      description: OAuth2 client credentials flow
      flows:
        clientCredentials:
          tokenUrl: "/oauth/token"
