# Default values for laa-hmrc-interface-production.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 4

ingress:
  path: /ping
  pathType: Exact
  hosts:
    - laa-hmrc-interface.cloud-platform.service.justice.gov.uk
  className: default
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: "laa-hmrc-interface-laa-hmrc-interface-service-api-laa-hmrc-interface-production-green"
    external-dns.alpha.kubernetes.io/aws-weight: "100"
    nginx.ingress.kubernetes.io/server-snippet: |
      if ($scheme = http) {
        return 444;
      }

deploy:
  host: laa-hmrc-interface.cloud-platform.service.justice.gov.uk
  settings__environment: live
  settings__sentry__environment: production

service_account:
  name: laa-hmrc-interface-production-irsa

sidekiq:
  replicaCount: 1
