# Default values for laa-hmrc-interface-uat.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

resources:
  limits:
    cpu: 500m
    memory: 1G
  requests:
    cpu: 10m
    memory: 125Mi

ingress:
  enabled: true
  className: default-non-prod
  annotations:
    external-dns.alpha.kubernetes.io/aws-weight: "100"
    nginx.ingress.kubernetes.io/server-snippet: |
      if ($scheme = http) {
        return 444;
      }

publicIngress:
  enabled: false

deploy:
  settings__environment: non-live
  settings__sentry__environment: uat

service_account:
  name: laa-hmrc-interface-uat-irsa

sidekiq:
  replicaCount: 1

smoke_test:
  use_case_one:
    first_name: 'Bailey'
    last_name: 'Yeates'
    nino: 'RA053692A'
    dob: '2000-08-11'
    start_date: '2023-10-01'
    end_date: '2023-12-31'
    correlation_id: '4331c7a8-7fbd-469c-aaca-7644eaeec6e1'
  use_case_two:
    first_name: 'Bailey'
    last_name: 'Yeates'
    nino: 'RA053692A'
    dob: '2000-08-11'
    start_date: '2023-10-01'
    end_date: '2023-12-31'
    correlation_id: '97c3c99e-5565-427e-ae03-ab354ce226cb'
  use_case_three:
    first_name: 'Bailey'
    last_name: 'Yeates'
    nino: 'RA053692A'
    dob: '2000-08-11'
    start_date: '2023-10-01'
    end_date: '2023-12-31'
    correlation_id: '9822b382-dadb-43ec-9976-67e989264b6a'
  use_case_four:
    first_name: 'Bailey'
    last_name: 'Yeates'
    nino: 'RA053692A'
    dob: '2000-08-11'
    start_date: '2023-10-01'
    end_date: '2023-12-31'
    correlation_id: 'a8809e73-bbdf-46d7-a607-51eb3c4a9c8a'
