# Default values for laa-hmrc-interface-staging.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

resources:
  limits:
    cpu: 500m
    memory: 1G
  requests:
    cpu: 10m
    memory: 125Mi

ingress:
  path: /ping
  pathType: Exact
  hosts:
    - laa-hmrc-interface-staging.cloud-platform.service.justice.gov.uk
  className: default-non-prod
  allowlist:
    enabled: true
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: "laa-hmrc-interface-laa-hmrc-interface-service-api-laa-hmrc-interface-staging-green"
    external-dns.alpha.kubernetes.io/aws-weight: "100"
    nginx.ingress.kubernetes.io/server-snippet: |
      if ($scheme = http) {
        return 444;
      }

deploy:
  host: laa-hmrc-interface-staging.cloud-platform.service.justice.gov.uk
  settings__environment: non-live
  settings__sentry__environment: staging

service_account:
  name: laa-hmrc-interface-staging-irsa

sidekiq:
  replicaCount: 1

# NOT NEEDED AS CIRCLECI RUNS SMOKE TESTS AGAINST UAT. REMOVE?!
smoke_test:
  use_case_one:
    first_name: 'Langley'
    last_name: 'Yorke'
    nino: 'MN212451D'
    dob: '1992-07-22'
    start_date: '2021-01-01'
    end_date: '2021-03-31'
    correlation_id: '4331c7a8-7fbd-469c-aaca-7644eaeec6e1'
  use_case_two:
    first_name: 'Langley'
    last_name: 'Yorke'
    nino: 'MN212451D'
    dob: '1992-07-22'
    start_date: '2021-01-01'
    end_date: '2021-03-31'
    correlation_id: '97c3c99e-5565-427e-ae03-ab354ce226cb'
  use_case_three:
    first_name: 'Langley'
    last_name: 'Yorke'
    nino: 'MN212451D'
    dob: '1992-07-22'
    start_date: '2021-01-01'
    end_date: '2021-03-31'
    correlation_id: '9822b382-dadb-43ec-9976-67e989264b6a'
  use_case_four:
    first_name: 'Langley'
    last_name: 'Yorke'
    nino: 'MN212451D'
    dob: '1992-07-22'
    start_date: '2021-01-01'
    end_date: '2021-03-31'
    correlation_id: 'a8809e73-bbdf-46d7-a607-51eb3c4a9c8a'
