credentials:
  host: &host 'https://fake.api'
  use_case_1:
    host: *host
    description: 'This is fake'
    hmrc_client_secret: 'NotASecret'
    hmrc_client_id: 'NotAClientID'
    hmrc_totp_secret: 'AlsoNotASecret'
