credentials:
  hmrc_host: 'https://fake.test.api'
  use_case_one:
    description: 'This is fake'
    hmrc_client_secret: 'NotASecret'
    hmrc_client_id: 'NotAClientID'
    hmrc_totp_secret: 'AlsoNotASecret'
  use_case_two:
    description: 'This is fake'
    hmrc_client_secret: 'NotASecret'
    hmrc_client_id: 'NotAClientID'
    hmrc_totp_secret: 'AlsoNotASecret'
  use_case_three:
    description: 'This is fake'
    hmrc_client_secret: 'NotASecret'
    hmrc_client_id: 'NotAClientID'
    hmrc_totp_secret: 'AlsoNotASecret'
  use_case_four:
    description: 'This is fake'
    hmrc_client_secret: 'NotASecret'
    hmrc_client_id: 'NotAClientID'
    hmrc_totp_secret: 'AlsoNotASecret'

smoke_test:
  use_case_one:
    nino: 'XX123456X'

sidekiq:
  username: 'fake_username'
  web_ui_password: 'fake_testing_password'

sentry:
  environment: 'test'

delay: 0
