name: Delete UAT release

on:
  pull_request:
    types:
      - closed

jobs:
  delete_uat_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Delete UAT release
        id: delete_uat
        uses: ministryofjustice/laa-civil-apply-delete-uat-release@v1.0.1
        with:
          k8s_cluster: ${{ secrets.K8S_GHA_UAT_CLUSTER_NAME }}
          k8s_cluster_cert: ${{ secrets.K8S_GHA_UAT_CLUSTER_CERT }}
          k8s_namespace: ${{ secrets.K8S_GHA_UAT_NAMESPACE }}
          k8s_token: ${{ secrets.K8S_GHA_UAT_TOKEN }}

      # Deletes an RDS instance database with a name
      # matching the branch/release. Note that it will
      # use a previous steps kubernetes authentication,
      # context and namespace.
      - name: Delete UAT RDS database
        shell: bash
        id: delete_uat_db
        run: |
          bin/uat_drop_db ${{ steps.delete_uat.outputs.release-name }}

      - name: Result
        shell: bash
        run: |
          echo ${{ steps.delete_uat.outputs.delete-message }}
          echo ${{ steps.delete_uat_db.outputs.drop-commmand-result }}
