name: Delete UAT release

on:
  pull_request:
    types:
      - closed

jobs:
  delete_uat_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Delete UAT release action
        id: delete_uat
        uses: ministryofjustice/laa-civil-apply-delete-uat-release@v1.0.0
        with:
          k8s_cluster: ${{ secrets.K8S_GHA_UAT_CLUSTER_NAME }}
          k8s_cluster_cert: ${{ secrets.K8S_GHA_UAT_CLUSTER_CERT }}
          k8s_namespace: ${{ secrets.K8S_GHA_UAT_NAMESPACE }}
          k8s_token: ${{ secrets.K8S_GHA_UAT_TOKEN }}

      - name: Delete DB
        shell: bash
        env:
          K8S_CLUSTER: ${{ secrets.K8S_GHA_UAT_CLUSTER_NAME }}
          K8S_CLUSTER_CERT: ${{ secrets.K8S_GHA_UAT_CLUSTER_CERT }}
          K8S_NAMESPACE: $${{ secrets.K8S_GHA_UAT_NAMESPACE }}
          K8S_TOKEN: ${{ secrets.K8S_GHA_UAT_TOKEN }}
        run: bin/uat_drop_db ${{ steps.delete_uat.outputs.release-name }}

      - uses: actions/checkout@v3
      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
        env:
          K8S_CLUSTER: ${{ secrets.K8S_GHA_UAT_CLUSTER_NAME }}
          K8S_NAMESPACE: $${{ secrets.K8S_GHA_UAT_NAMESPACE }}
        timeout-minutes: 15
        with:
          limit-access-to-actor: true

      - name: Result
        shell: bash
        run: echo ${{ steps.delete_uat.outputs.delete-message }}
